parameters:
#    file_attach_inline.example.class: RC\PHPCR\FileAttachInlineBundle\Example

services:
#    file_attach_inline.example:
#        class: %file_attach_inline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
